spring:
  application:
    name: microbackend

server:
  port: 8080
  shutdown: graceful

app:
  version: ${APP_VERSION:local}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
