apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microplatform.fullname" . }}-backend
  labels:
    {{- include "microplatform.labels" . | nindent 4 }}
    app.kubernetes.io/name: microbackend
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microbackend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microbackend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: microplatform
      annotations:
        lab.openai.dev/image-tag: {{ .Values.backend.image.tag | quote }}
    spec:
      {{- include "microplatform.imagePullSecrets" . | nindent 6 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: microbackend
              app.kubernetes.io/instance: {{ .Release.Name }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: APP_VERSION
              value: {{ .Values.backend.image.tag | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop: ["ALL"]
      terminationGracePeriodSeconds: 30
