imagePullSecrets: []

backend:
  replicaCount: 2
  image:
    repository: registry.example.invalid/group/project/backend
    tag: local
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 30081
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 2
  image:
    repository: registry.example.invalid/group/project/frontend
    tag: local
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 192Mi
