apiVersion: batch/v1
kind: CronJob
metadata:
  name: tarefa-periodica
  namespace: estudo-containers
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: tarefa
              image: alpine:3.21
              command: ["sh", "-c", "date; echo execução periódica"]
