apiVersion: batch/v1
kind: Job
metadata:
  name: processamento
  namespace: estudo-containers
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: tarefa
          image: alpine:3.21
          command: ["sh", "-c", "echo Início; sleep 5; echo Concluído"]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
