apiVersion: v1
kind: Service
metadata:
  name: {{ include "microplatform.fullname" . }}-frontend
  labels:
    {{- include "microplatform.labels" . | nindent 4 }}
    app.kubernetes.io/name: microfrontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: microfrontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
